[build]
  publish = "frontend"
  command = "npm install && npm run build"

[build.environment]
  NODE_ENV = "production"
  
[[functions]]
  url = "/.netlify/functions/server"
  runtime = "nodejs18.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 5000